package sd.mtn.ocs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://172.21.24.100:8680/services/QueryMgrService/#%7Bhttp%3A%2F%2Fwww.huawei.com%2Fbme%2Fcbsinterface%2Fquerymgr%7DQueryMgrService?wsdl",
  targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr", name="QueryMgr")
@XmlSeeAlso(
  { com.huawei.bme.cbsinterface.querymgr.ObjectFactory.class, com.huawei.bme.cbsinterface.newsubscriber.ObjectFactory.class, com.huawei.bme.cbsinterface.query.ObjectFactory.class, com.huawei.bme.cbsinterface.subscribe.ObjectFactory.class, com.huawei.bme.cbsinterface.acctcredit.ObjectFactory.class, com.huawei.bme.cbsinterface.common.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface QueryMgr
{
  @WebMethod(action="queryCustomer")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="queryCustomer", output="http://www.huawei.com/bme/cbsinterface/querymgr/QueryMgr/queryCustomerResponse")
  @WebResult(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
    partName="QueryCustomerResultMsg", name="QueryCustomerResultMsg")
  public com.huawei.bme.cbsinterface.querymgr.QueryCustomerResultMsg queryCustomer(@WebParam(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
      partName="QueryCustomerRequestMsg", name="QueryCustomerRequestMsg")
    com.huawei.bme.cbsinterface.querymgr.QueryCustomerRequestMsg QueryCustomerRequestMsg);

  @WebMethod(action="queryBalance")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="queryBalance", output="http://www.huawei.com/bme/cbsinterface/querymgr/QueryMgr/queryBalanceResponse")
  @WebResult(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
    partName="QueryBalanceResultMsg", name="QueryBalanceResultMsg")
  public com.huawei.bme.cbsinterface.querymgr.QueryBalanceResultMsg queryBalance(@WebParam(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
      partName="QueryBalanceRequestMsg", name="QueryBalanceRequestMsg")
    com.huawei.bme.cbsinterface.querymgr.QueryBalanceRequestMsg QueryBalanceRequestMsg);

  @WebMethod(action="queryProductOrder")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="queryProductOrder", output="http://www.huawei.com/bme/cbsinterface/querymgr/QueryMgr/queryProductOrderResponse")
  @WebResult(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
    partName="QueryProductOrderResultMsg", name="QueryProductOrderResultMsg")
  public com.huawei.bme.cbsinterface.querymgr.QueryProductOrderResultMsg queryProductOrder(@WebParam(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
      partName="QueryProductOrderRequestMsg", name="QueryProductOrderRequestMsg")
    com.huawei.bme.cbsinterface.querymgr.QueryProductOrderRequestMsg QueryProductOrderRequestMsg);

  @WebMethod(action="queryLastTranInfo")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="queryLastTranInfo", output="http://www.huawei.com/bme/cbsinterface/querymgr/QueryMgr/queryLastTranInfoResponse")
  @WebResult(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
    partName="QueryLastTranInfoResultMsg", name="QueryLastTranInfoResultMsg")
  public com.huawei.bme.cbsinterface.querymgr.QueryLastTranInfoResultMsg queryLastTranInfo(@WebParam(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
      partName="QueryLastTranInfoRequestMsg", name="QueryLastTranInfoRequestMsg")
    com.huawei.bme.cbsinterface.querymgr.QueryLastTranInfoRequestMsg QueryLastTranInfoRequestMsg);

  @WebMethod(action="queryBalanceTransferInfo")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="queryBalanceTransferInfo", output="http://www.huawei.com/bme/cbsinterface/querymgr/QueryMgr/queryBalanceTransferInfoResponse")
  @WebResult(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
    partName="QueryBalanceTransferInfoResultMsg", name="QueryBalanceTransferInfoResultMsg")
  public com.huawei.bme.cbsinterface.querymgr.QueryBalanceTransferInfoResultMsg queryBalanceTransferInfo(@WebParam(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
      partName="QueryBalanceTransferInfoRequestMsg", name="QueryBalanceTransferInfoRequestMsg")
    com.huawei.bme.cbsinterface.querymgr.QueryBalanceTransferInfoRequestMsg QueryBalanceTransferInfoRequestMsg);

  @WebMethod(action="querySubCosID")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="querySubCosID", output="http://www.huawei.com/bme/cbsinterface/querymgr/QueryMgr/querySubCosIDResponse")
  @WebResult(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
    partName="QuerySubCosIDResultMsg", name="QuerySubCosIDResultMsg")
  public com.huawei.bme.cbsinterface.querymgr.QuerySubCosIDResultMsg querySubCosID(@WebParam(targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr",
      partName="QuerySubCosIDRequestMsg", name="QuerySubCosIDRequestMsg")
    com.huawei.bme.cbsinterface.querymgr.QuerySubCosIDRequestMsg QuerySubCosIDRequestMsg);
}
