package sd.mtn.ocs;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://172.21.24.100:8680/services/QueryMgrService/#%7Bhttp%3A%2F%2Fwww.huawei.com%2Fbme%2Fcbsinterface%2Fquerymgr%7DQueryMgrService?wsdl",
  targetNamespace="http://www.huawei.com/bme/cbsinterface/querymgr", name="QueryMgrService")
public class QueryMgrService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("sd.mtn.ocs.QueryMgrService");
      URL baseUrl = QueryMgrService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            QueryMgrService.class.getResource("http://172.21.24.100:8680/services/QueryMgrService/#%7Bhttp%3A%2F%2Fwww.huawei.com%2Fbme%2Fcbsinterface%2Fquerymgr%7DQueryMgrService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://172.21.24.100:8680/services/QueryMgrService/#%7Bhttp%3A%2F%2Fwww.huawei.com%2Fbme%2Fcbsinterface%2Fquerymgr%7DQueryMgrService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://172.21.24.100:8680/services/QueryMgrService/#%7Bhttp%3A%2F%2Fwww.huawei.com%2Fbme%2Fcbsinterface%2Fquerymgr%7DQueryMgrService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://172.21.24.100:8680/services/QueryMgrService/#%7Bhttp%3A%2F%2Fwww.huawei.com%2Fbme%2Fcbsinterface%2Fquerymgr%7DQueryMgrService?wsdl",
          e);
    }
  }

  public QueryMgrService()
  {
    super(wsdlLocationURL,
          new QName("http://www.huawei.com/bme/cbsinterface/querymgr",
                    "QueryMgrService"));
  }

  public QueryMgrService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="QueryMgrServicePort")
  public sd.mtn.ocs.QueryMgr getQueryMgrServicePort()
  {
    return (sd.mtn.ocs.QueryMgr) super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/querymgr",
                                                         "QueryMgrServicePort"),
                                               sd.mtn.ocs.QueryMgr.class);
  }

  @WebEndpoint(name="QueryMgrServicePort")
  public sd.mtn.ocs.QueryMgr getQueryMgrServicePort(WebServiceFeature... features)
  {
    return (sd.mtn.ocs.QueryMgr) super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/querymgr",
                                                         "QueryMgrServicePort"),
                                               sd.mtn.ocs.QueryMgr.class,
                                               features);
  }
}
