package sd.mtn.cbos;

import com.gemalto.ggs.cbos.wswrapper.ws.ConsumerInfoResponse;
import com.gemalto.ggs.cbos.wswrapper.ws.ConsumerInformation;
import com.gemalto.ggs.cbos.wswrapper.ws.GmppResponse;
import com.gemalto.ggs.cbos.wswrapper.ws.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://172.16.198.10/GMPPMediatorUSSDServiceBean/GMPPUSSDService?wsdl",
  targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/", name="GMPPUSSDService")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface GMPPUSSDService
{
  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/distributeRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/distributeResponse")
  @ResponseWrapper(localName="distributeResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.DistributeResponse")
  @RequestWrapper(localName="distribute", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.Distribute")
  @WebResult(targetNamespace="")
  public GmppResponse distribute(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="destinationIdentifier")
    String destinationIdentifier);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/rechargeRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/rechargeResponse")
  @ResponseWrapper(localName="rechargeResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.RechargeResponse")
  @RequestWrapper(localName="recharge", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.Recharge")
  @WebResult(targetNamespace="")
  public GmppResponse recharge(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="payeeId")
    String payeeId, @WebParam(targetNamespace="", name="customerPayeeId")
    String customerPayeeId, @WebParam(targetNamespace="", name="transactionName")
    String transactionName);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/registerConsumerAtMerchantRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/registerConsumerAtMerchantResponse")
  @ResponseWrapper(localName="registerConsumerAtMerchantResponse",
    targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.RegisterConsumerAtMerchantResponse")
  @RequestWrapper(localName="registerConsumerAtMerchant", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.RegisterConsumerAtMerchant")
  @WebResult(targetNamespace="")
  public GmppResponse registerConsumerAtMerchant(@WebParam(targetNamespace="",
      name="consumerIdentifier")
    String consumerIdentifier, @WebParam(targetNamespace="", name="managerMSISDN")
    String managerMSISDN, @WebParam(targetNamespace="", name="pin")
    String pin);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/completeConsumerRegistrationRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/completeConsumerRegistrationResponse")
  @ResponseWrapper(localName="completeConsumerRegistrationResponse",
    targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CompleteConsumerRegistrationResponse")
  @RequestWrapper(localName="completeConsumerRegistration",
    targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CompleteConsumerRegistration")
  @WebResult(targetNamespace="")
  public GmppResponse completeConsumerRegistration(@WebParam(targetNamespace="",
      name="consumerIdentifier")
    String consumerIdentifier, @WebParam(targetNamespace="", name="managerMSISDN")
    String managerMSISDN, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="serviceProviderId")
    String serviceProviderId, @WebParam(targetNamespace="", name="tan")
    String tan, @WebParam(targetNamespace="", name="kycType")
    String kycType, @WebParam(targetNamespace="", name="kycValue")
    String kycValue, @WebParam(targetNamespace="", name="flowId")
    String flowId);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/selfTopUpRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/selfTopUpResponse")
  @ResponseWrapper(localName="selfTopUpResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SelfTopUpResponse")
  @RequestWrapper(localName="selfTopUp", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SelfTopUp")
  @WebResult(targetNamespace="")
  public GmppResponse selfTopUp(@WebParam(targetNamespace="", name="payeeId")
    String payeeId, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="consumerIdentifier")
    String consumerIdentifier, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="transactionName")
    String transactionName);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/payBillRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/payBillResponse")
  @ResponseWrapper(localName="payBillResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.PayBillResponse")
  @RequestWrapper(localName="payBill", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.PayBill")
  @WebResult(targetNamespace="")
  public GmppResponse payBill(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="payeeId")
    String payeeId, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="customerPayeeId")
    String customerPayeeId, @WebParam(targetNamespace="", name="transactionName")
    String transactionName);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/transferMoneyP2PRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/transferMoneyP2PResponse")
  @ResponseWrapper(localName="transferMoneyP2PResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.TransferMoneyP2PResponse")
  @RequestWrapper(localName="transferMoneyP2P", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.TransferMoneyP2P")
  @WebResult(targetNamespace="")
  public GmppResponse transferMoneyP2P(@WebParam(targetNamespace="", name="consumerIdentifier")
    String consumerIdentifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="destinationIdentifier")
    String destinationIdentifier);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/cashInRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/cashInResponse")
  @ResponseWrapper(localName="cashInResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CashInResponse")
  @RequestWrapper(localName="cashIn", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CashIn")
  @WebResult(targetNamespace="")
  public GmppResponse cashIn(@WebParam(targetNamespace="", name="managerMSISDN")
    String managerMSISDN, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="destinationConsumerIdentifier")
    String destinationConsumerIdentifier);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/startCashOutRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/startCashOutResponse")
  @ResponseWrapper(localName="startCashOutResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.StartCashOutResponse")
  @RequestWrapper(localName="startCashOut", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.StartCashOut")
  @WebResult(targetNamespace="")
  public GmppResponse startCashOut(@WebParam(targetNamespace="", name="sourceIdetifier")
    String sourceIdetifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="cashOutAt")
    String cashOutAt, @WebParam(targetNamespace="", name="cashoutAll")
    Boolean cashoutAll);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/completeCashOutAtMerchantRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/completeCashOutAtMerchantResponse")
  @ResponseWrapper(localName="completeCashOutAtMerchantResponse",
    targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CompleteCashOutAtMerchantResponse")
  @RequestWrapper(localName="completeCashOutAtMerchant", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CompleteCashOutAtMerchant")
  @WebResult(targetNamespace="")
  public GmppResponse completeCashOutAtMerchant(@WebParam(targetNamespace="",
      name="managerMSISDN")
    String managerMSISDN, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="transactionId")
    String transactionId, @WebParam(targetNamespace="", name="tan")
    String tan);

  @WebMethod(operationName="p2sBuy")
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/p2sBuyRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/p2sBuyResponse")
  @ResponseWrapper(localName="p2sBuyResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.P2SBuyResponse")
  @RequestWrapper(localName="p2sBuy", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.P2SBuy")
  @WebResult(targetNamespace="")
  public GmppResponse p2SBuy(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="destinationIdentifier")
    String destinationIdentifier, @WebParam(targetNamespace="", name="transactionName")
    String transactionName);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/getSVABalanceRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/getSVABalanceResponse")
  @ResponseWrapper(localName="getSVABalanceResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.GetSVABalanceResponse")
  @RequestWrapper(localName="getSVABalance", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.GetSVABalance")
  @WebResult(targetNamespace="")
  public GmppResponse getSVABalance(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="isConsumer")
    Boolean isConsumer);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/getLastTransactionsRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/getLastTransactionsResponse")
  @ResponseWrapper(localName="getLastTransactionsResponse",
    targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.GetLastTransactionsResponse")
  @RequestWrapper(localName="getLastTransactions", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.GetLastTransactions")
  @WebResult(targetNamespace="")
  public GmppResponse getLastTransactions(@WebParam(targetNamespace="",
      name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="isConsumer")
    Boolean isConsumer);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/svaToCardRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/svaToCardResponse")
  @ResponseWrapper(localName="svaToCardResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SvaToCardResponse")
  @RequestWrapper(localName="svaToCard", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SvaToCard")
  @WebResult(targetNamespace="")
  public GmppResponse svaToCard(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/cardToSVARequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/cardToSVAResponse")
  @ResponseWrapper(localName="cardToSVAResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CardToSVAResponse")
  @RequestWrapper(localName="cardToSVA", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.CardToSVA")
  @WebResult(targetNamespace="")
  public GmppResponse cardToSVA(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="amount")
    String amount, @WebParam(targetNamespace="", name="pin")
    String pin, @WebParam(targetNamespace="", name="ipin")
    String ipin, @WebParam(targetNamespace="", name="expDate")
    String expDate);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/changePinRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/changePinResponse")
  @ResponseWrapper(localName="changePinResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.ChangePinResponse")
  @RequestWrapper(localName="changePin", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.ChangePin")
  @WebResult(targetNamespace="")
  public GmppResponse changePin(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="newPin")
    String newPin, @WebParam(targetNamespace="", name="oldPIN")
    String oldPIN, @WebParam(targetNamespace="", name="isConsumer")
    Boolean isConsumer);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/selfLockRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/selfLockResponse")
  @ResponseWrapper(localName="selfLockResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SelfLockResponse")
  @RequestWrapper(localName="selfLock", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SelfLock")
  @WebResult(targetNamespace="")
  public GmppResponse selfLock(@WebParam(targetNamespace="", name="consumerIdentifier")
    String consumerIdentifier, @WebParam(targetNamespace="", name="pin")
    String pin);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/selfUnlockRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/selfUnlockResponse")
  @ResponseWrapper(localName="selfUnlockResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SelfUnlockResponse")
  @RequestWrapper(localName="selfUnlock", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.SelfUnlock")
  @WebResult(targetNamespace="")
  public GmppResponse selfUnlock(@WebParam(targetNamespace="", name="sourceIdentifier")
    String sourceIdentifier, @WebParam(targetNamespace="", name="pin")
    String pin);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/updateConsumerInfoRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/updateConsumerInfoResponse")
  @ResponseWrapper(localName="updateConsumerInfoResponse",
    targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.UpdateConsumerInfoResponse")
  @RequestWrapper(localName="updateConsumerInfo", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.UpdateConsumerInfo")
  @WebResult(targetNamespace="")
  public GmppResponse updateConsumerInfo(@WebParam(targetNamespace="",
      name="consumerInformation")
    ConsumerInformation consumerInformation);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/getConsumerInfoRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/getConsumerInfoResponse")
  @ResponseWrapper(localName="getConsumerInfoResponse", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.GetConsumerInfoResponse")
  @RequestWrapper(localName="getConsumerInfo", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.GetConsumerInfo")
  @WebResult(targetNamespace="")
  public ConsumerInfoResponse getConsumerInfo(@WebParam(targetNamespace="",
      name="consumerIdentifier")
    String consumerIdentifier, @WebParam(targetNamespace="", name="managerMSISDN")
    String managerMSISDN, @WebParam(targetNamespace="", name="pin")
    String pin);

  @WebMethod
  @Action(input="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/consumerRegistrationRequest",
    output="http://ws.wswrapper.cbos.ggs.gemalto.com/GMPPUSSDService/consumerRegistrationResponse")
  @ResponseWrapper(localName="consumerRegistrationResponse",
    targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.ConsumerRegistrationResponse")
  @RequestWrapper(localName="consumerRegistration", targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/",
    className="com.gemalto.ggs.cbos.wswrapper.ws.ConsumerRegistration")
  @WebResult(targetNamespace="")
  public GmppResponse consumerRegistration(@WebParam(targetNamespace="",
      name="serviceProviderId")
    String serviceProviderId, @WebParam(targetNamespace="", name="consumerIdentifier")
    String consumerIdentifier, @WebParam(targetNamespace="", name="kycType")
    String kycType, @WebParam(targetNamespace="", name="kycValue")
    String kycValue);
}
