package sd.mtn.cbos;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://172.16.198.10/GMPPMediatorUSSDServiceBean/GMPPUSSDService?wsdl",
  targetNamespace="http://ws.wswrapper.cbos.ggs.gemalto.com/", name="GMPPUSSDService")
public class GMPPUSSDService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("sd.mtn.cbos.GMPPUSSDService_Service");
      URL baseUrl = GMPPUSSDService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            GMPPUSSDService_Service.class.getResource("http://172.16.198.10/GMPPMediatorUSSDServiceBean/GMPPUSSDService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://172.16.198.10/GMPPMediatorUSSDServiceBean/GMPPUSSDService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://172.16.198.10/GMPPMediatorUSSDServiceBean/GMPPUSSDService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://172.16.198.10/GMPPMediatorUSSDServiceBean/GMPPUSSDService?wsdl",
          e);
    }
  }

  public GMPPUSSDService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://ws.wswrapper.cbos.ggs.gemalto.com/",
                    "GMPPUSSDService"));
  }

  public GMPPUSSDService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="GMPPUSSDServicePort")
  public GMPPUSSDService getGMPPUSSDServicePort()
  {
    return (GMPPUSSDService) super.getPort(new QName("http://ws.wswrapper.cbos.ggs.gemalto.com/",
                                                     "GMPPUSSDServicePort"),
                                           GMPPUSSDService.class);
  }

  @WebEndpoint(name="GMPPUSSDServicePort")
  public GMPPUSSDService getGMPPUSSDServicePort(WebServiceFeature... features)
  {
    return (GMPPUSSDService) super.getPort(new QName("http://ws.wswrapper.cbos.ggs.gemalto.com/",
                                                     "GMPPUSSDServicePort"),
                                           GMPPUSSDService.class,
                                           features);
  }
}
